# Generated by Django 5.0.6 on 2024-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0003_remove_tweet_nickname_tweet_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
