# Generated by Django 5.0.6 on 2024-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0006_tweet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='foto',
            field=models.ImageField(null=True, upload_to='downloads/'),
        ),
    ]
