# Generated by Django 5.0.6 on 2024-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0008_alter_tweet_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='foto',
        ),
    ]
