# Generated by Django 5.0.6 on 2024-07-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0010_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
